### ISSUE TITLE
UI shows 0 words found despite words being found

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/bogdle#14]
![E56BF316-FEC0-409B-BCD2-5B483AC2D1DB](https://user-images.githubusercontent.com/10620708/197548074-bc126605-5589-4fb9-b996-9cff2b6b6722.jpeg)

For several days my UI has been stuck in a bad state where (most notably) the words found count never increases. The coloration of words seems off, too, but I don’t understand that system well enough to know exactly what’s wrong there.

Issue is localized to this device (iOS), and this browser session (Chrome), but is not present in incognito mode, etc. Likely a cookie issue?

**Comment by michaelchadwick** [comment]
Thanks for the bug report! I've been doing a lot of updates over the week, and it's possible something got messed up in the config stuff (it's all `localStorage`, btw, no cookies used). Colors have changed a bit, too, and thanks for the reminder to add some verbiage about it in the 'Help' modal.

* Desktop browser: the easiest way to fix this is to go into the Developer Console and then to the Application tab. Clear the `bogdle-state-daily` key and it should re-orient things.
* Mobile browser: there is probably a "clear data" option in Settings->Chrome somewhere

Note: this will erase any progress you've made (games finished, words found), but the app is in more or less in beta, so I don't have a better solution right now.
